baseURL: https://shuyiguoportfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Shuyi Guo
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      An LBS Student Majoring in Masters in Financial Analysis.
    title: Hi, my name is Shuyi GUO
  blog: {}
  contact:
    address:
      - city: London, ST 00000
        country: United Kingdom 
        street: Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: sguo.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social: 
     # - icon: fa-twitter
     #   label: Twitter
     #   url: https://www.twitter.com
    #  - icon: fa-facebook
     #   label: Facebook
      #  url: https://www.facebook.com
    #  - icon: fa-instagram
    #    label: Instagram
    #    url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/ShuyiGUOLBS
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/shu-yi-guo-7709a0152
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Find out more about Shuyi
        title: About me
        url: blogs/self_intro
      - image: Wall_Street.jpg
        subtitle: Banking and Finance
        title: My Career Aspiration
        url: blogs/career #link the "slug"
      - image: Player.jpg
        subtitle: sports and gaming
        title: My Hobbies
        url: blogs/my_hobbies
      - image: Coding.jpg
        subtitle: EDA and Visualization
        title: My First Codes
        url: blogs/first
      - image: imm-statistic.jpg
        subtitle: Hypothesis testing
        title: My Second Codes
        url: blogs/second
   #   - image: pic06.jpg
    #    subtitle: Feugiat Amet Tempus
    #    title: Etiam
     #   url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: no
    subtitle: "Feel free to get in touch with me via different contacts below. I really love to make more friends here in the 
      the UK. Looking forward to chat about everything from professional life to personal life."
    title: Connect with me!
    url: blogs
